[lintspec]
paths = []
exclude = []
inheritdoc = false
notice_or_dev = false
skip_version_detection = false

[output]
json = false
compact = false
sort = false

[constructor]
notice = "ignored"
dev = "ignored"
param = "required"

[enum]
notice = "required"
dev = "ignored"
param = "ignored"

[error]
notice = "required"
dev = "ignored"
param = "required"

[event]
notice = "required"
dev = "ignored"
param = "required"

[function.private]
notice = "ignored"
dev = "required"
param = "required"
return = "required"

[function.internal]
notice = "ignored"
dev = "required"
param = "required"
return = "required"

[function.public]
notice = "required"
dev = "ignored"
param = "required"
return = "required"

[function.external]
notice = "required"
dev = "ignored"
param = "required"
return = "required"

[modifier]
notice = "ignored"
dev = "required"
param = "required"

[struct]
notice = "required"
dev = "ignored"
param = "required"

[variable.private]
notice = "ignored"
dev = "required"

[variable.internal]
notice = "ignored"
dev = "required"

[variable.public]
notice = "required"
dev = "ignored"
return = "required"
